from datetime import UTC, datetime, timedelta, timezone

import pytest
from alembic.autogenerate import render_python_code
from alembic.operations.ops import CreateTableOp, UpgradeOps
from fastapi.testclient import TestClient
from pydantic import ValidationError
from sqlalchemy import Column
from sqlalchemy.dialects.postgresql.base import PGDialect

from app.api.main import create_app
from app.config import Settings, parse_database_url
from app.db.base import UTCDateTime
from app.db.migrations import render_database_type
from app.db.session import Database


def test_database_url_is_required_when_database_is_used(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("APP_ENV", "test")
    with pytest.raises(ValueError, match="DATABASE_URL"):
        Settings().require_database_url()


@pytest.mark.parametrize(
    "url",
    [
        "invalid",
        "sqlite+aiosqlite:///test.db",
        "postgresql://localhost/test",
        "postgresql+asyncpg:///",
    ],
)
def test_database_rejects_invalid_url(url: str, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("APP_ENV", "test")
    monkeypatch.setenv("DATABASE_URL", url)
    with pytest.raises(ValidationError, match="DATABASE_URL"):
        Settings()


def test_local_database_cannot_target_remote_host(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("APP_ENV", "local")
    monkeypatch.setenv("DATABASE_URL", "postgresql+asyncpg://reader:private@production/db")
    with pytest.raises(ValidationError, match="回环地址") as error:
        Settings()
    assert "private" not in str(error.value)


def test_database_password_is_hidden(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("APP_ENV", "test")
    monkeypatch.setenv("DATABASE_URL", "postgresql+asyncpg://user:private@127.0.0.1/test")
    settings = Settings()
    assert "private" not in repr(settings)
    assert settings.require_database_url().password == "private"


def test_utc_type_normalizes_aware_time_and_rejects_naive_time() -> None:
    column_type = UTCDateTime()
    dialect = PGDialect()  # type: ignore[no-untyped-call]  # SQLAlchemy 未标注该构造函数。
    value = datetime(2026, 10, 6, 8, tzinfo=timezone(timedelta(hours=8)))
    expected = datetime(2026, 10, 6, tzinfo=UTC)
    assert column_type.process_bind_param(value, dialect) == expected
    assert column_type.process_result_value(value, dialect) == expected
    assert column_type.process_bind_param(None, dialect) is None
    assert column_type.compile(dialect=dialect) == "TIMESTAMP WITH TIME ZONE"
    with pytest.raises(ValueError, match="带时区"):
        column_type.process_bind_param(datetime(2026, 10, 6), dialect)


@pytest.mark.asyncio
async def test_sessions_are_independent_and_do_not_expire_after_commit() -> None:
    database = Database(parse_database_url("postgresql+asyncpg://127.0.0.1/unused"))
    try:
        async with database.session() as first, database.session() as second:
            assert first is not second
            assert not first.sync_session.expire_on_commit
            assert not second.sync_session.expire_on_commit
    finally:
        await database.dispose()


def test_api_database_lifespan_does_not_require_connection(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("APP_ENV", "test")
    monkeypatch.setenv("DATABASE_URL", "postgresql+asyncpg://127.0.0.1:1/unused")
    application = create_app()
    with TestClient(application) as client:
        assert isinstance(application.state.database, Database)
        assert client.get("/health").json() == {"status": "ok"}


def test_autogenerated_migration_uses_native_timezone_type() -> None:
    operations = UpgradeOps([CreateTableOp("probe", [Column("created_at", UTCDateTime())])])
    code = render_python_code(operations, render_item=render_database_type)
    assert "sa.DateTime(timezone=True)" in code
    assert "app.db.base" not in code
